#
# Example: unique
#
- hosts:
  - localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    list1:
    - user1
    - user1
    - user2

    list2:
    - host: local1
      user: user1
    - host: local1
      user: user1
    - host: local2
      user: user2

  pre_tasks:

  roles:

  tasks:
  - debug:
      msg: '{{ list1 | unique }}'

  - debug:
      msg: >
        {{
          list2 | json_query('[].{"host": host, "user": user}') | unique
        }}
